// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGZekgDXG4eDNPwx0fjL9Ez8Aq8dzr8Y',
    appId: '1:27019397436:web:9aa637dd9568f431fa3639',
    messagingSenderId: '27019397436',
    projectId: 'matrimonio-a4767',
    authDomain: 'matrimonio-a4767.firebaseapp.com',
    storageBucket: 'matrimonio-a4767.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9s3S23TZE8ZzK6JXVjG3VSdcrhj3dhW4',
    appId: '1:27019397436:android:29c03654cb936301fa3639',
    messagingSenderId: '27019397436',
    projectId: 'matrimonio-a4767',
    storageBucket: 'matrimonio-a4767.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0phI1M1PRr1DmU0DPzmjLcN7gMdQbAg',
    appId: '1:27019397436:ios:c88f29e53557218afa3639',
    messagingSenderId: '27019397436',
    projectId: 'matrimonio-a4767',
    storageBucket: 'matrimonio-a4767.firebasestorage.app',
    iosBundleId: 'com.example.matrimonio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0phI1M1PRr1DmU0DPzmjLcN7gMdQbAg',
    appId: '1:27019397436:ios:c88f29e53557218afa3639',
    messagingSenderId: '27019397436',
    projectId: 'matrimonio-a4767',
    storageBucket: 'matrimonio-a4767.firebasestorage.app',
    iosBundleId: 'com.example.matrimonio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUGZekgDXG4eDNPwx0fjL9Ez8Aq8dzr8Y',
    appId: '1:27019397436:web:1e06a13b1aba295ffa3639',
    messagingSenderId: '27019397436',
    projectId: 'matrimonio-a4767',
    authDomain: 'matrimonio-a4767.firebaseapp.com',
    storageBucket: 'matrimonio-a4767.firebasestorage.app',
  );
}
